---
development:
  cloud_name: dvxxpxcbi
  api_key: '583624699231939'
  api_secret: xa3fzNUF6YKQnUUgz6pUHqb-yOo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvxxpxcbi
  api_key: '583624699231939'
  api_secret: xa3fzNUF6YKQnUUgz6pUHqb-yOo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvxxpxcbi
  api_key: '583624699231939'
  api_secret: xa3fzNUF6YKQnUUgz6pUHqb-yOo
  enhance_image_tag: true
  static_image_support: false
